version: '3'

services:
  backend-main:
    image: mjatwood/thumbathon-backend:latest
    command: /bin/sh -c "npm run typeorm:run && npm run start"
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - thumbathon-net

  backend-event-bus:
    image: mjatwood/thumbathon-backend:latest
    command: /bin/sh -c "npm run start:event-bus"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./downloads:/tmp
    networks:
      - thumbathon-net

  frontend:
    image: mjatwood/thumbathon-frontend:latest
    ports:
      - "3000:80"
    networks:
      - thumbathon-net

  postgres:
    image: postgres:15
    environment:
      - "POSTGRES_USER=${DATABASE_USERNAME}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - thumbathon-net
  
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - thumbathon-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
      
volumes:
  pgdata:

networks:
  thumbathon-net:
    driver: bridge
