name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BACKEND_IMAGE: mjatwood/thumbathon-backend:latest
  FRONTEND_IMAGE: mjatwood/thumbathon-frontend:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Set up Docker Buildx and QEMU
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build and push both backend and frontend images
    - name: Build and push images
      run: |
        docker buildx build --push --platform linux/amd64,linux/arm64 -f ./backend/Dockerfile -t ${{ env.BACKEND_IMAGE }} ./backend
        docker buildx build --push --platform linux/amd64,linux/arm64 -f ./frontend/Dockerfile -t ${{ env.FRONTEND_IMAGE }} ./frontend
