name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
        # Login to Docker Hub
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build backend image
      run: |
        docker build -f ./backend/Dockerfile -t mjatwood/thumbathon-backend:latest ./backend
        docker push mjatwood/thumbathon-backend:latest

    - name: Build frontend image
      run: |
        docker build -f ./frontend/Dockerfile -t mjatwood/thumbathon-frontend:latest ./frontend
        docker push mjatwood/thumbathon-frontend:latest


