name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build backend image
      run: docker build -f ./backend/Dockerfile -t mjatwood/thumbathon-backend:latest ./backend

    - name: Build frontend image
      run: docker build -f ./frontend/Dockerfile -t mjatwood/thumbathon-frontend:latest ./backend

