name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
        # Login to Docker Hub
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Build backend image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -f ./backend/Dockerfile -t mjatwood/thumbathon-backend:latest ./backend
        docker push mjatwood/thumbathon-backend:latest

    - name: Build frontend image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -f ./frontend/Dockerfile -t mjatwood/thumbathon-frontend:latest ./frontend
        docker push mjatwood/thumbathon-frontend:latest


